# Generated by Django 4.2.2 on 2023-07-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_data',
            field=models.JSONField(blank=True, default=dict, max_length=100),
        ),
    ]
